server {
  listen 80;
  listen [::]:80;
  server_name mise.zabrown.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl;
  server_name mise.zabrown.com;

  ssl_certificate     /etc/letsencrypt/live/zabrown.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/zabrown.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location / {
    proxy_pass http://127.0.0.1:4173/;
    include proxy_params;
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
